privia_solution/config/routes.rb
Rails.application.routes.draw do

  resources :imports do
    collection {post :import}
  end
  
  resources :line_items

  root 'imports#index'

end

privia_solution/app/models/import.rb
class Import < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  require 'csv'

  def total_value
    total_value = 0
    self.line_items.each do |f|
      total_value += f.item_price * f.purchase_count
    end
    return total_value
  end


  def self.import(file)
    import = Import.create!
    CSV.foreach(file.path, {headers: true, col_sep: "\t"} ) do |row|
        import_row = row.to_hash
        import.line_items.create(
        purchaser_name: import_row["purchaser name"],
        item_description: import_row["item description"],
        item_price: import_row["item price"],
        purchase_count: import_row["purchase count"],
        merchant_address: import_row["merchant address"],
        merchant_name: import_row["merchant name"]
        )
    end # end CSV.foreach
  end # end self.import(file)

end

privia_solution/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :import
end

privia_solution/app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: [:show, :edit, :update, :destroy]

  # GET /imports
  # GET /imports.json
  def index
    @imports = Import.all
  end

  # GET /imports/1
  # GET /imports/1.json
  def show
    @import = Import.find(params[:id])
    @line_items = @import.line_items
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # GET /imports/1/edit
  def edit
  end

  # POST /imports
  # POST /imports.json
  def create
    @import = Import.new(import_params)

    respond_to do |format|
      if @import.save
        format.html { redirect_to @import, notice: 'Import was successfully created.' }
        format.json { render :show, status: :created, location: @import }
      else
        format.html { render :new }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/1
  # PATCH/PUT /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to @import, notice: 'Import was successfully updated.' }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1
  # DELETE /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Import.import(params[:file])
    redirect_to root_url, notice: "Import Successful"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Import.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_params
      params.fetch(:import, {})
    end
end

privia_solution/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to :back, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:purchaser_name, :item_description, :item_price, :purchase_count, :merchant_address, :merchant_name)
    end
end

privia_solution/app/helpers/imports_helper.rb
module ImportsHelper
end

privia_solution/app/helpers/line_items_helper.rb
module LineItemsHelper
end

privia_solution/app/views/imports/_form.html.erb
<%= form_for(@import) do |f| %>
  <% if @import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% @import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

privia_solution/app/views/imports/_import.html.erb
<h4>New Import</h4>
<%= form_tag import_imports_path, multipart: true, class: "navbar-form navbar-left search-form" do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import File" %>
<% end %>

privia_solution/app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form' %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

privia_solution/app/views/imports/index.html.erb
<%= render 'import' %>

<p id="notice"><%= notice %></p>

<h1>Listing Imports</h1>

<table>
  <thead>
    <tr>
      <th>Import Id</th>
      <th>View Import</th>
      <th>Delete Import</th>
      <th>Total Amount Gross Revenue</th>
    </tr>
  </thead>

  <tbody>
    <% @imports.each do |import| %>
      <tr>
        <td><%= import.id %></td>
        <td><%= link_to 'Show', import %></td>
        <td><%= link_to 'Destroy', import, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= number_to_currency(import.total_value) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

privia_solution/app/views/imports/new.html.erb
<h1>New Import</h1>

<%= render 'form' %>

<%= link_to 'Back', imports_path %>

privia_solution/app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "Import ##{@import.id}" %></h1>
<h2><%= "Total Value = #{number_to_currency(@import.total_value)}"%></h2>

<%= link_to 'Home', imports_path %>

<table>
  <thead>
    <tr>
      <th>Purchaser Name</th>
      <th>Item Description</th>
      <th>Item Price</th>
      <th>Purchase Count</th>
      <th>Merchant Address</th>
      <th>Merchant Name</th>
    </tr>
  </thead>
  <tbody>
    <% if !@line_items.blank? %>
      <% for item in @line_items %>
        <%= render 'line_items/form', :@line_item => item %>
      <% end %>
    <% else %>

  </tbody>
</table>
<% end %>

privia_solution/app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <tr>
    <td class="field">
      <%= f.text_field :purchaser_name %>
    </td>
    <td class="field">
      <%= f.text_area :item_description %>
    </td>
    <td class="field">
      <%= f.number_field :item_price %>
    </td>
    <td class="field">
      <%= f.number_field :purchase_count %>
    </td>
    <td class="field">
      <%= f.text_field :merchant_address %>
    </td>
    <td class="field">
      <%= f.text_field :merchant_name %>
    </td>
    <td class="actions">
      <%= f.submit %>
    </td>
  </tr>
<% end %>

privia_solution/app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

privia_solution/app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Purchaser name</th>
      <th>Item description</th>
      <th>Item price</th>
      <th>Purchase count</th>
      <th>Merchant address</th>
      <th>Merchant name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.purchaser_name %></td>
        <td><%= line_item.item_description %></td>
        <td><%= line_item.item_price %></td>
        <td><%= line_item.purchase_count %></td>
        <td><%= line_item.merchant_address %></td>
        <td><%= line_item.merchant_name %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

privia_solution/app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

privia_solution/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Purchaser name:</strong>
  <%= @line_item.purchaser_name %>
</p>

<p>
  <strong>Item description:</strong>
  <%= @line_item.item_description %>
</p>

<p>
  <strong>Item price:</strong>
  <%= @line_item.item_price %>
</p>

<p>
  <strong>Purchase count:</strong>
  <%= @line_item.purchase_count %>
</p>

<p>
  <strong>Merchant address:</strong>
  <%= @line_item.merchant_address %>
</p>

<p>
  <strong>Merchant name:</strong>
  <%= @line_item.merchant_name %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', imports_path(@line_item.import_id) %>